site_name: Storebrowse Classic Password Insertion for Citrix Workspace app for Linux
site_description: Storebrowse Classic Password Insertion for Citrix Workspace app for Linux
theme_dir: citrix-sdk
markdown_extensions:
  - admonition
  - codehilite
  - toc:
     anchorlink: True
pages:

- Home: index.md
